import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import "dotenv/config";

const adapter = new PrismaPg(process.env.DIRECT_URL ?? process.env.DATABASE_URL!);
const prisma = new PrismaClient({ adapter });

const IQAC = [
  { slug: "team",                        title: "IQAC Team",                      subtitle: "Committee members, external experts, and structure", content: "The IQAC (Internal Quality Assurance Cell) is the governing administrative cell driving institutional benchmarks, academic audits, and strategic deployment frameworks.\n\nCoordinator: Dr. A. Sridhar, Department of Mathematics\n\nCommittee Members:\n1. Dr. G. Ramasamy — Assistant Professor, Department of Chemistry\n2. Dr. D. Ramasamy — Assistant Professor, Department of Chemistry\n3. Dr. S. Senthil Kumar — Assistant Professor, Department of Mathematics\n\nThe IQAC ensures continuous improvement in academic and administrative performance of the institution.", order: 1 },
  { slug: "activities",                  title: "IQAC Activities",                subtitle: "Quality initiatives, seminars, and event reports", content: "IQAC conducts various quality enhancement activities throughout the academic year including:\n\n• Faculty Development Programmes (FDP)\n• Student Satisfaction Surveys\n• Academic Audit and Peer Review\n• Seminars and Workshops on Quality Education\n• Industry-Academia Interface Programmes\n• Green Campus Initiatives\n• ICT-enabled Teaching Learning Practices\n\nAll activities are documented and submitted as part of the Annual Quality Assurance Report (AQAR).", order: 2 },
  { slug: "best-practices",              title: "Best Practices",                 subtitle: "Institutional benchmarks and core value models", content: "GTMC follows two key best practices as part of its NAAC accreditation framework:\n\nBest Practice 1: Value Education Programme\nThe college conducts regular value education sessions to inculcate moral, ethical and social values among students. Guest lectures, workshops and community service activities are organized.\n\nBest Practice 2: Green Campus Initiative\nThe college maintains a lush 47-acre green campus with dedicated efforts towards environmental sustainability including tree plantation drives, waste management, and energy conservation measures.", order: 3 },
  { slug: "institutional-distinctiveness", title: "Institutional Distinctiveness", subtitle: "Our unique educational vision and priority areas", content: "Govt. Thirumagal Mills College, Gudiyattam stands distinct in the following ways:\n\n1. Tri-State Convergence: Located at the junction of Tamil Nadu, Andhra Pradesh and Karnataka, the college serves students from three states fostering multilingual and multicultural harmony.\n\n2. Defence Contribution: The college has a proud tradition of educating children of defence personnel. Many alumni serve in the Army, CRPF, BSF and TBSF.\n\n3. Rural Empowerment: Established with the vision of providing quality higher education to students from socio-economically backward rural communities.\n\n4. Government Institution: As a government-aided college, education is made accessible and affordable to all sections of society.", order: 4 },
  { slug: "program-outcomes",            title: "Program Outcomes",               subtitle: "Expected graduate attributes and course objectives", content: "Program Outcomes (POs) for all UG and PG programmes at GTMC:\n\nPO1 – Disciplinary Knowledge: Apply knowledge of the discipline to solve real-world problems.\nPO2 – Critical Thinking: Analyse and evaluate information to make informed decisions.\nPO3 – Problem Solving: Identify, formulate and solve complex problems.\nPO4 – Communication Skills: Communicate effectively in oral and written forms.\nPO5 – Teamwork: Work effectively as an individual and as a member of a team.\nPO6 – Ethics: Apply ethical principles and commit to professional ethics.\nPO7 – Environment and Sustainability: Understand the impact of professional solutions on society and environment.\nPO8 – Life-long Learning: Recognise the need for and engage in independent and life-long learning.", order: 5 },
  { slug: "sss-report",                  title: "SSS Report 2021-22",             subtitle: "Student Satisfaction Survey analysis metrics", content: "The Student Satisfaction Survey (SSS) 2021-22 was conducted as per NAAC guidelines to assess student satisfaction across various parameters.\n\nKey Findings:\n• Teaching-Learning Process: 4.2/5\n• Library Facilities: 4.0/5\n• Sports & Extracurricular: 3.9/5\n• Campus Infrastructure: 4.1/5\n• Placement Support: 3.8/5\n• Overall Satisfaction: 4.1/5\n\nTotal Respondents: 850 students across all departments.\n\nThe survey results have been used to identify areas for improvement and implement corrective measures.", order: 6 },
  { slug: "nirf-2022",                   title: "NIRF Information 2022",          subtitle: "National Institutional Ranking Framework data analytics", content: "NIRF 2022 Data Submission — Govt. Thirumagal Mills College, Gudiyattam\n\nThe college has submitted data to the National Institutional Ranking Framework (NIRF) 2022 under the Ministry of Education, Government of India.\n\nKey Parameters Submitted:\n• Teaching, Learning & Resources (TLR)\n• Research and Professional Practice (RP)\n• Graduation Outcomes (GO)\n• Outreach and Inclusivity (OI)\n• Perception (PR)\n\nPlease upload the official NIRF 2022 PDF document for download.", order: 7 },
  { slug: "aicte-eoa",                   title: "AICTE EOA 2021-22",              subtitle: "Extension of Approval status documentation", content: "AICTE Extension of Approval (EOA) for the Academic Year 2021-22\n\nGovt. Thirumagal Mills College has received the Extension of Approval from the All India Council for Technical Education (AICTE) for the academic year 2021-22.\n\nApproved Programmes:\n• BCA — Bachelor of Computer Applications\n• BBA — Bachelor of Business Administration\n\nThe EOA confirms compliance with AICTE norms and standards for technical education programmes offered by the institution.", order: 8 },
  { slug: "minutes",                     title: "Minutes of Meetings",            subtitle: "Statutory cell reviews and resolution summaries", content: "Minutes of IQAC Meetings — Govt. Thirumagal Mills College\n\nThe IQAC conducts regular meetings to review quality parameters, plan activities and monitor implementation of quality initiatives.\n\nMeeting Schedule:\n• Quarterly meetings (4 per academic year)\n• Special meetings as required\n\nAgenda items typically include:\n• Review of previous meeting action points\n• Academic audit findings\n• Student feedback analysis\n• Faculty development plans\n• Infrastructure improvement proposals\n• NAAC/NIRF preparation updates\n\nPlease upload the official minutes PDF documents.", order: 9 },
  { slug: "future-plan",                 title: "Future Plan",                    subtitle: "Strategic developmental pathways and milestones", content: "Strategic Future Development Plan — GTMC\n\nShort-term Goals (1-2 Years):\n• Establish a dedicated Research Centre\n• Introduce skill development courses in collaboration with industry\n• Upgrade computer labs with latest hardware and software\n• Strengthen placement cell with more industry tie-ups\n\nMedium-term Goals (3-5 Years):\n• Apply for Autonomous College status\n• Introduce new PG programmes in emerging fields\n• Establish a Centre of Excellence in Data Science\n• Develop a digital library with e-resources\n\nLong-term Goals (5+ Years):\n• Achieve NAAC A Grade accreditation\n• Establish industry-sponsored research chairs\n• Develop international academic collaborations", order: 10 },
  { slug: "rti-pdf",                     title: "RTI PDF",                        subtitle: "Right to Information basic framework logs", content: "Right to Information (RTI) Act 2005 — Information Disclosure\n\nGovt. Thirumagal Mills College is committed to transparency and accountability under the Right to Information Act 2005.\n\nPublic Information Officer (PIO):\nThe Principal, Govt. Thirumagal Mills College, Gudiyattam — 632 602\n\nInformation available under RTI:\n• Institutional details and history\n• Academic programmes offered\n• Faculty details and qualifications\n• Financial statements and audit reports\n• Admission procedures and fee structure\n• Infrastructure details\n\nPlease upload the official RTI document PDF.", order: 11 },
  { slug: "rti-act-new",                 title: "RTI Act-2005 New",               subtitle: "Statutory governance and transparency declarations", content: "RTI Act 2005 — Updated Framework\n\nAs per the Right to Information Act 2005, Govt. Thirumagal Mills College proactively discloses the following information:\n\nSection 4(1)(b) Disclosures:\n1. Particulars of organisation, functions and duties\n2. Powers and duties of officers and employees\n3. Procedure followed in decision making\n4. Norms set for discharge of functions\n5. Rules, regulations, instructions, manuals\n6. Categories of documents held\n7. Particulars of consultative committees\n8. Directory of officers and employees\n9. Monthly remuneration of officers\n10. Budget allocated to each agency\n\nPlease upload the updated RTI Act document PDF.", order: 12 },
];

const NIRF = [
  { slug: "nirf-college-2025", title: "NIRF - College 2025",   subtitle: "NIRF Data Submission for College Category 2025", content: "National Institutional Ranking Framework (NIRF) — College Category 2025\n\nGovt. Thirumagal Mills College has submitted data for NIRF College Category ranking 2025 to the Ministry of Education, Government of India.\n\nParameters evaluated:\n• Teaching, Learning & Resources (TLR) — 30%\n• Research and Professional Practice (RP) — 30%\n• Graduation Outcomes (GO) — 20%\n• Outreach and Inclusivity (OI) — 10%\n• Perception (PR) — 10%\n\nPlease upload the official NIRF 2025 submission PDF.", order: 1 },
  { slug: "nirf-overall-2024", title: "NIRF - Overall 2024",   subtitle: "NIRF Overall Category Ranking 2024", content: "National Institutional Ranking Framework (NIRF) — Overall Category 2024\n\nData submitted for NIRF Overall Category ranking 2024.\n\nThe overall ranking considers performance across all five parameters with equal weightage to teaching quality, research output, graduation outcomes, inclusivity and perception.\n\nPlease upload the official NIRF Overall 2024 PDF document.", order: 2 },
  { slug: "nirf-college-2024", title: "NIRF - College 2024",   subtitle: "NIRF Data Submission for College Category 2024", content: "National Institutional Ranking Framework (NIRF) — College Category 2024\n\nData submitted for NIRF College Category ranking 2024 to the Ministry of Education.\n\nPlease upload the official NIRF College 2024 PDF document.", order: 3 },
  { slug: "nirf-college-2023", title: "NIRF - College 2023",   subtitle: "NIRF Data Submission for College Category 2023", content: "National Institutional Ranking Framework (NIRF) — College Category 2023\n\nData submitted for NIRF College Category ranking 2023 to the Ministry of Education.\n\nPlease upload the official NIRF College 2023 PDF document.", order: 4 },
  { slug: "nirf-overall-2023", title: "NIRF - Overall 2023",   subtitle: "NIRF Overall Category Ranking 2023", content: "National Institutional Ranking Framework (NIRF) — Overall Category 2023\n\nData submitted for NIRF Overall Category ranking 2023.\n\nPlease upload the official NIRF Overall 2023 PDF document.", order: 5 },
];

const AQAR = [
  { slug: "aqar-2017-18", title: "AQAR 2017-18", subtitle: "Annual Quality Assurance Report for Academic Year 2017-18", content: "Annual Quality Assurance Report (AQAR) — 2017-18\n\nSubmitted to NAAC as part of the post-accreditation quality sustenance measures.\n\nKey Highlights 2017-18:\n• Total student enrolment: 2,450\n• Faculty strength: 98\n• New programmes introduced: Nil\n• Research papers published: 12\n• Seminars/Workshops conducted: 8\n• Placement percentage: 72%\n• Pass percentage: 88%\n\nPlease upload the official AQAR 2017-18 PDF document.", order: 1 },
  { slug: "aqar-2018-19", title: "AQAR 2018-19", subtitle: "Annual Quality Assurance Report for Academic Year 2018-19", content: "Annual Quality Assurance Report (AQAR) — 2018-19\n\nSubmitted to NAAC as part of the post-accreditation quality sustenance measures.\n\nKey Highlights 2018-19:\n• Total student enrolment: 2,580\n• Faculty strength: 102\n• New programmes introduced: PG History\n• Research papers published: 18\n• Seminars/Workshops conducted: 11\n• Placement percentage: 75%\n• Pass percentage: 89%\n\nPlease upload the official AQAR 2018-19 PDF document.", order: 2 },
  { slug: "aqar-2019-20", title: "AQAR 2019-20", subtitle: "Annual Quality Assurance Report for Academic Year 2019-20", content: "Annual Quality Assurance Report (AQAR) — 2019-20\n\nSubmitted to NAAC as part of the post-accreditation quality sustenance measures.\n\nKey Highlights 2019-20:\n• Total student enrolment: 2,690\n• Faculty strength: 105\n• Online classes initiated due to COVID-19\n• Research papers published: 22\n• Seminars/Workshops conducted: 9\n• Placement percentage: 70% (impacted by COVID)\n• Pass percentage: 87%\n\nPlease upload the official AQAR 2019-20 PDF document.", order: 3 },
  { slug: "aqar-2020-21", title: "AQAR 2020-21", subtitle: "Annual Quality Assurance Report for Academic Year 2020-21", content: "Annual Quality Assurance Report (AQAR) — 2020-21\n\nSubmitted to NAAC as part of the post-accreditation quality sustenance measures.\n\nKey Highlights 2020-21:\n• Total student enrolment: 2,720\n• Faculty strength: 108\n• Full online mode of teaching due to COVID-19\n• ICT tools adopted: Google Meet, Zoom, Google Classroom\n• Research papers published: 25\n• Seminars/Workshops conducted: 14 (online)\n• Placement percentage: 78%\n• Pass percentage: 91%\n\nPlease upload the official AQAR 2020-21 PDF document.", order: 4 },
];

async function main() {
  console.log("Seeding IQAC entries...");
  for (const item of IQAC) {
    await prisma.dynamicSection.upsert({
      where: { group_slug: { group: "iqac", slug: item.slug } },
      update: { title: item.title, subtitle: item.subtitle, content: item.content, order: item.order },
      create: { group: "iqac", ...item, pdfUrl: "", active: true },
    });
  }

  console.log("Seeding NIRF entries...");
  for (const item of NIRF) {
    await prisma.dynamicSection.upsert({
      where: { group_slug: { group: "nirf", slug: item.slug } },
      update: { title: item.title, subtitle: item.subtitle, content: item.content, order: item.order },
      create: { group: "nirf", ...item, pdfUrl: "", active: true },
    });
  }

  console.log("Seeding AQAR entries...");
  for (const item of AQAR) {
    await prisma.dynamicSection.upsert({
      where: { group_slug: { group: "aqar", slug: item.slug } },
      update: { title: item.title, subtitle: item.subtitle, content: item.content, order: item.order },
      create: { group: "aqar", ...item, pdfUrl: "", active: true },
    });
  }

  console.log(`✅ Seeded ${IQAC.length} IQAC + ${NIRF.length} NIRF + ${AQAR.length} AQAR entries`);
  await prisma.$disconnect();
}

main().catch((e) => { console.error(e); process.exit(1); });
