/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisionMissionRouteImport } from './routes/vision-mission'
import { Route as TransportRouteImport } from './routes/transport'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ScholarshipsRouteImport } from './routes/scholarships'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as PrincipalMessageRouteImport } from './routes/principal-message'
import { Route as PlacementRouteImport } from './routes/placement'
import { Route as OfficeRouteImport } from './routes/office'
import { Route as NewsRouteImport } from './routes/news'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as InfrastructureRouteImport } from './routes/infrastructure'
import { Route as HostelRouteImport } from './routes/hostel'
import { Route as HodRouteImport } from './routes/hod'
import { Route as GoverningCouncilRouteImport } from './routes/governing-council'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as FacultyRouteImport } from './routes/faculty'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CalenderRouteImport } from './routes/calender'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AlumniRouteImport } from './routes/alumni'
import { Route as AdmissionRouteImport } from './routes/admission'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DepartmentsIndexRouteImport } from './routes/departments.index'
import { Route as StudentLoginRouteImport } from './routes/student/login'
import { Route as StudentDashboardRouteImport } from './routes/student/dashboard'
import { Route as ReportsIdRouteImport } from './routes/reports.$id'
import { Route as NirfTabIdRouteImport } from './routes/nirf.$tabId'
import { Route as IqacTabIdRouteImport } from './routes/iqac.$tabId'
import { Route as DepartmentsDeptIdRouteImport } from './routes/departments.$deptId'
import { Route as CoursesUgRouteImport } from './routes/courses.ug'
import { Route as CoursesResearchRouteImport } from './routes/courses.research'
import { Route as CoursesPgRouteImport } from './routes/courses.pg'
import { Route as CoursesEMaterialsRouteImport } from './routes/courses.e-materials'
import { Route as ComplianceIdRouteImport } from './routes/compliance.$id'
import { Route as AqarTabIdRouteImport } from './routes/aqar.$tabId'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as ActivitiesTabIdRouteImport } from './routes/activities.$tabId'
import { Route as AdminLayoutUsersRouteImport } from './routes/admin/_layout.users'
import { Route as AdminLayoutTestimonialsRouteImport } from './routes/admin/_layout.testimonials'
import { Route as AdminLayoutStudentsRouteImport } from './routes/admin/_layout.students'
import { Route as AdminLayoutPrincipalRouteImport } from './routes/admin/_layout.principal'
import { Route as AdminLayoutNewsRouteImport } from './routes/admin/_layout.news'
import { Route as AdminLayoutImagesRouteImport } from './routes/admin/_layout.images'
import { Route as AdminLayoutFeedbackRouteImport } from './routes/admin/_layout.feedback'
import { Route as AdminLayoutFacultyRouteImport } from './routes/admin/_layout.faculty'
import { Route as AdminLayoutEventsRouteImport } from './routes/admin/_layout.events'
import { Route as AdminLayoutEnquiriesRouteImport } from './routes/admin/_layout.enquiries'
import { Route as AdminLayoutDynamicSectionsRouteImport } from './routes/admin/_layout.dynamic-sections'
import { Route as AdminLayoutDashboardRouteImport } from './routes/admin/_layout.dashboard'
import { Route as AdminLayoutCoursesRouteImport } from './routes/admin/_layout.courses'
import { Route as AdminLayoutContentRouteImport } from './routes/admin/_layout.content'
import { Route as AdminLayoutApplicationsRouteImport } from './routes/admin/_layout.applications'
import { Route as AdminLayoutAnnouncementsRouteImport } from './routes/admin/_layout.announcements'
import { Route as AdminLayoutAlumniRouteImport } from './routes/admin/_layout.alumni'

const VisionMissionRoute = VisionMissionRouteImport.update({
  id: '/vision-mission',
  path: '/vision-mission',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportRoute = TransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipsRoute = ScholarshipsRouteImport.update({
  id: '/scholarships',
  path: '/scholarships',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const PrincipalMessageRoute = PrincipalMessageRouteImport.update({
  id: '/principal-message',
  path: '/principal-message',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacementRoute = PlacementRouteImport.update({
  id: '/placement',
  path: '/placement',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeRoute = OfficeRouteImport.update({
  id: '/office',
  path: '/office',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructureRoute = InfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => rootRouteImport,
} as any)
const HostelRoute = HostelRouteImport.update({
  id: '/hostel',
  path: '/hostel',
  getParentRoute: () => rootRouteImport,
} as any)
const HodRoute = HodRouteImport.update({
  id: '/hod',
  path: '/hod',
  getParentRoute: () => rootRouteImport,
} as any)
const GoverningCouncilRoute = GoverningCouncilRouteImport.update({
  id: '/governing-council',
  path: '/governing-council',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRoute = FacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CalenderRoute = CalenderRouteImport.update({
  id: '/calender',
  path: '/calender',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AlumniRoute = AlumniRouteImport.update({
  id: '/alumni',
  path: '/alumni',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionRoute = AdmissionRouteImport.update({
  id: '/admission',
  path: '/admission',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsIndexRoute = DepartmentsIndexRouteImport.update({
  id: '/departments/',
  path: '/departments/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLoginRoute = StudentLoginRouteImport.update({
  id: '/student/login',
  path: '/student/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIdRoute = ReportsIdRouteImport.update({
  id: '/reports/$id',
  path: '/reports/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NirfTabIdRoute = NirfTabIdRouteImport.update({
  id: '/nirf/$tabId',
  path: '/nirf/$tabId',
  getParentRoute: () => rootRouteImport,
} as any)
const IqacTabIdRoute = IqacTabIdRouteImport.update({
  id: '/iqac/$tabId',
  path: '/iqac/$tabId',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsDeptIdRoute = DepartmentsDeptIdRouteImport.update({
  id: '/departments/$deptId',
  path: '/departments/$deptId',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesUgRoute = CoursesUgRouteImport.update({
  id: '/courses/ug',
  path: '/courses/ug',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesResearchRoute = CoursesResearchRouteImport.update({
  id: '/courses/research',
  path: '/courses/research',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesPgRoute = CoursesPgRouteImport.update({
  id: '/courses/pg',
  path: '/courses/pg',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesEMaterialsRoute = CoursesEMaterialsRouteImport.update({
  id: '/courses/e-materials',
  path: '/courses/e-materials',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceIdRoute = ComplianceIdRouteImport.update({
  id: '/compliance/$id',
  path: '/compliance/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AqarTabIdRoute = AqarTabIdRouteImport.update({
  id: '/aqar/$tabId',
  path: '/aqar/$tabId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesTabIdRoute = ActivitiesTabIdRouteImport.update({
  id: '/activities/$tabId',
  path: '/activities/$tabId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutUsersRoute = AdminLayoutUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutTestimonialsRoute = AdminLayoutTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutStudentsRoute = AdminLayoutStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutPrincipalRoute = AdminLayoutPrincipalRouteImport.update({
  id: '/principal',
  path: '/principal',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutNewsRoute = AdminLayoutNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutImagesRoute = AdminLayoutImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutFeedbackRoute = AdminLayoutFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutFacultyRoute = AdminLayoutFacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutEventsRoute = AdminLayoutEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutEnquiriesRoute = AdminLayoutEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutDynamicSectionsRoute =
  AdminLayoutDynamicSectionsRouteImport.update({
    id: '/dynamic-sections',
    path: '/dynamic-sections',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutDashboardRoute = AdminLayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutCoursesRoute = AdminLayoutCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutContentRoute = AdminLayoutContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutApplicationsRoute = AdminLayoutApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutAnnouncementsRoute =
  AdminLayoutAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutAlumniRoute = AdminLayoutAlumniRouteImport.update({
  id: '/alumni',
  path: '/alumni',
  getParentRoute: () => AdminLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admission': typeof AdmissionRoute
  '/alumni': typeof AlumniRoute
  '/apply': typeof ApplyRoute
  '/calender': typeof CalenderRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/faculty': typeof FacultyRoute
  '/feedback': typeof FeedbackRoute
  '/gallery': typeof GalleryRoute
  '/governing-council': typeof GoverningCouncilRoute
  '/hod': typeof HodRoute
  '/hostel': typeof HostelRoute
  '/infrastructure': typeof InfrastructureRoute
  '/library': typeof LibraryRoute
  '/news': typeof NewsRoute
  '/office': typeof OfficeRoute
  '/placement': typeof PlacementRoute
  '/principal-message': typeof PrincipalMessageRoute
  '/rules': typeof RulesRoute
  '/scholarships': typeof ScholarshipsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/timeline': typeof TimelineRoute
  '/transport': typeof TransportRoute
  '/vision-mission': typeof VisionMissionRoute
  '/activities/$tabId': typeof ActivitiesTabIdRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/aqar/$tabId': typeof AqarTabIdRoute
  '/compliance/$id': typeof ComplianceIdRoute
  '/courses/e-materials': typeof CoursesEMaterialsRoute
  '/courses/pg': typeof CoursesPgRoute
  '/courses/research': typeof CoursesResearchRoute
  '/courses/ug': typeof CoursesUgRoute
  '/departments/$deptId': typeof DepartmentsDeptIdRoute
  '/iqac/$tabId': typeof IqacTabIdRoute
  '/nirf/$tabId': typeof NirfTabIdRoute
  '/reports/$id': typeof ReportsIdRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/login': typeof StudentLoginRoute
  '/departments/': typeof DepartmentsIndexRoute
  '/admin/alumni': typeof AdminLayoutAlumniRoute
  '/admin/announcements': typeof AdminLayoutAnnouncementsRoute
  '/admin/applications': typeof AdminLayoutApplicationsRoute
  '/admin/content': typeof AdminLayoutContentRoute
  '/admin/courses': typeof AdminLayoutCoursesRoute
  '/admin/dashboard': typeof AdminLayoutDashboardRoute
  '/admin/dynamic-sections': typeof AdminLayoutDynamicSectionsRoute
  '/admin/enquiries': typeof AdminLayoutEnquiriesRoute
  '/admin/events': typeof AdminLayoutEventsRoute
  '/admin/faculty': typeof AdminLayoutFacultyRoute
  '/admin/feedback': typeof AdminLayoutFeedbackRoute
  '/admin/images': typeof AdminLayoutImagesRoute
  '/admin/news': typeof AdminLayoutNewsRoute
  '/admin/principal': typeof AdminLayoutPrincipalRoute
  '/admin/students': typeof AdminLayoutStudentsRoute
  '/admin/testimonials': typeof AdminLayoutTestimonialsRoute
  '/admin/users': typeof AdminLayoutUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admission': typeof AdmissionRoute
  '/alumni': typeof AlumniRoute
  '/apply': typeof ApplyRoute
  '/calender': typeof CalenderRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/faculty': typeof FacultyRoute
  '/feedback': typeof FeedbackRoute
  '/gallery': typeof GalleryRoute
  '/governing-council': typeof GoverningCouncilRoute
  '/hod': typeof HodRoute
  '/hostel': typeof HostelRoute
  '/infrastructure': typeof InfrastructureRoute
  '/library': typeof LibraryRoute
  '/news': typeof NewsRoute
  '/office': typeof OfficeRoute
  '/placement': typeof PlacementRoute
  '/principal-message': typeof PrincipalMessageRoute
  '/rules': typeof RulesRoute
  '/scholarships': typeof ScholarshipsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/timeline': typeof TimelineRoute
  '/transport': typeof TransportRoute
  '/vision-mission': typeof VisionMissionRoute
  '/activities/$tabId': typeof ActivitiesTabIdRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/aqar/$tabId': typeof AqarTabIdRoute
  '/compliance/$id': typeof ComplianceIdRoute
  '/courses/e-materials': typeof CoursesEMaterialsRoute
  '/courses/pg': typeof CoursesPgRoute
  '/courses/research': typeof CoursesResearchRoute
  '/courses/ug': typeof CoursesUgRoute
  '/departments/$deptId': typeof DepartmentsDeptIdRoute
  '/iqac/$tabId': typeof IqacTabIdRoute
  '/nirf/$tabId': typeof NirfTabIdRoute
  '/reports/$id': typeof ReportsIdRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/login': typeof StudentLoginRoute
  '/departments': typeof DepartmentsIndexRoute
  '/admin/alumni': typeof AdminLayoutAlumniRoute
  '/admin/announcements': typeof AdminLayoutAnnouncementsRoute
  '/admin/applications': typeof AdminLayoutApplicationsRoute
  '/admin/content': typeof AdminLayoutContentRoute
  '/admin/courses': typeof AdminLayoutCoursesRoute
  '/admin/dashboard': typeof AdminLayoutDashboardRoute
  '/admin/dynamic-sections': typeof AdminLayoutDynamicSectionsRoute
  '/admin/enquiries': typeof AdminLayoutEnquiriesRoute
  '/admin/events': typeof AdminLayoutEventsRoute
  '/admin/faculty': typeof AdminLayoutFacultyRoute
  '/admin/feedback': typeof AdminLayoutFeedbackRoute
  '/admin/images': typeof AdminLayoutImagesRoute
  '/admin/news': typeof AdminLayoutNewsRoute
  '/admin/principal': typeof AdminLayoutPrincipalRoute
  '/admin/students': typeof AdminLayoutStudentsRoute
  '/admin/testimonials': typeof AdminLayoutTestimonialsRoute
  '/admin/users': typeof AdminLayoutUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admission': typeof AdmissionRoute
  '/alumni': typeof AlumniRoute
  '/apply': typeof ApplyRoute
  '/calender': typeof CalenderRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/faculty': typeof FacultyRoute
  '/feedback': typeof FeedbackRoute
  '/gallery': typeof GalleryRoute
  '/governing-council': typeof GoverningCouncilRoute
  '/hod': typeof HodRoute
  '/hostel': typeof HostelRoute
  '/infrastructure': typeof InfrastructureRoute
  '/library': typeof LibraryRoute
  '/news': typeof NewsRoute
  '/office': typeof OfficeRoute
  '/placement': typeof PlacementRoute
  '/principal-message': typeof PrincipalMessageRoute
  '/rules': typeof RulesRoute
  '/scholarships': typeof ScholarshipsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/timeline': typeof TimelineRoute
  '/transport': typeof TransportRoute
  '/vision-mission': typeof VisionMissionRoute
  '/activities/$tabId': typeof ActivitiesTabIdRoute
  '/admin/_layout': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/aqar/$tabId': typeof AqarTabIdRoute
  '/compliance/$id': typeof ComplianceIdRoute
  '/courses/e-materials': typeof CoursesEMaterialsRoute
  '/courses/pg': typeof CoursesPgRoute
  '/courses/research': typeof CoursesResearchRoute
  '/courses/ug': typeof CoursesUgRoute
  '/departments/$deptId': typeof DepartmentsDeptIdRoute
  '/iqac/$tabId': typeof IqacTabIdRoute
  '/nirf/$tabId': typeof NirfTabIdRoute
  '/reports/$id': typeof ReportsIdRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/login': typeof StudentLoginRoute
  '/departments/': typeof DepartmentsIndexRoute
  '/admin/_layout/alumni': typeof AdminLayoutAlumniRoute
  '/admin/_layout/announcements': typeof AdminLayoutAnnouncementsRoute
  '/admin/_layout/applications': typeof AdminLayoutApplicationsRoute
  '/admin/_layout/content': typeof AdminLayoutContentRoute
  '/admin/_layout/courses': typeof AdminLayoutCoursesRoute
  '/admin/_layout/dashboard': typeof AdminLayoutDashboardRoute
  '/admin/_layout/dynamic-sections': typeof AdminLayoutDynamicSectionsRoute
  '/admin/_layout/enquiries': typeof AdminLayoutEnquiriesRoute
  '/admin/_layout/events': typeof AdminLayoutEventsRoute
  '/admin/_layout/faculty': typeof AdminLayoutFacultyRoute
  '/admin/_layout/feedback': typeof AdminLayoutFeedbackRoute
  '/admin/_layout/images': typeof AdminLayoutImagesRoute
  '/admin/_layout/news': typeof AdminLayoutNewsRoute
  '/admin/_layout/principal': typeof AdminLayoutPrincipalRoute
  '/admin/_layout/students': typeof AdminLayoutStudentsRoute
  '/admin/_layout/testimonials': typeof AdminLayoutTestimonialsRoute
  '/admin/_layout/users': typeof AdminLayoutUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admission'
    | '/alumni'
    | '/apply'
    | '/calender'
    | '/contact'
    | '/events'
    | '/faculty'
    | '/feedback'
    | '/gallery'
    | '/governing-council'
    | '/hod'
    | '/hostel'
    | '/infrastructure'
    | '/library'
    | '/news'
    | '/office'
    | '/placement'
    | '/principal-message'
    | '/rules'
    | '/scholarships'
    | '/sitemap.xml'
    | '/timeline'
    | '/transport'
    | '/vision-mission'
    | '/activities/$tabId'
    | '/admin'
    | '/admin/login'
    | '/aqar/$tabId'
    | '/compliance/$id'
    | '/courses/e-materials'
    | '/courses/pg'
    | '/courses/research'
    | '/courses/ug'
    | '/departments/$deptId'
    | '/iqac/$tabId'
    | '/nirf/$tabId'
    | '/reports/$id'
    | '/student/dashboard'
    | '/student/login'
    | '/departments/'
    | '/admin/alumni'
    | '/admin/announcements'
    | '/admin/applications'
    | '/admin/content'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/dynamic-sections'
    | '/admin/enquiries'
    | '/admin/events'
    | '/admin/faculty'
    | '/admin/feedback'
    | '/admin/images'
    | '/admin/news'
    | '/admin/principal'
    | '/admin/students'
    | '/admin/testimonials'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admission'
    | '/alumni'
    | '/apply'
    | '/calender'
    | '/contact'
    | '/events'
    | '/faculty'
    | '/feedback'
    | '/gallery'
    | '/governing-council'
    | '/hod'
    | '/hostel'
    | '/infrastructure'
    | '/library'
    | '/news'
    | '/office'
    | '/placement'
    | '/principal-message'
    | '/rules'
    | '/scholarships'
    | '/sitemap.xml'
    | '/timeline'
    | '/transport'
    | '/vision-mission'
    | '/activities/$tabId'
    | '/admin'
    | '/admin/login'
    | '/aqar/$tabId'
    | '/compliance/$id'
    | '/courses/e-materials'
    | '/courses/pg'
    | '/courses/research'
    | '/courses/ug'
    | '/departments/$deptId'
    | '/iqac/$tabId'
    | '/nirf/$tabId'
    | '/reports/$id'
    | '/student/dashboard'
    | '/student/login'
    | '/departments'
    | '/admin/alumni'
    | '/admin/announcements'
    | '/admin/applications'
    | '/admin/content'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/dynamic-sections'
    | '/admin/enquiries'
    | '/admin/events'
    | '/admin/faculty'
    | '/admin/feedback'
    | '/admin/images'
    | '/admin/news'
    | '/admin/principal'
    | '/admin/students'
    | '/admin/testimonials'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admission'
    | '/alumni'
    | '/apply'
    | '/calender'
    | '/contact'
    | '/events'
    | '/faculty'
    | '/feedback'
    | '/gallery'
    | '/governing-council'
    | '/hod'
    | '/hostel'
    | '/infrastructure'
    | '/library'
    | '/news'
    | '/office'
    | '/placement'
    | '/principal-message'
    | '/rules'
    | '/scholarships'
    | '/sitemap.xml'
    | '/timeline'
    | '/transport'
    | '/vision-mission'
    | '/activities/$tabId'
    | '/admin/_layout'
    | '/admin/login'
    | '/aqar/$tabId'
    | '/compliance/$id'
    | '/courses/e-materials'
    | '/courses/pg'
    | '/courses/research'
    | '/courses/ug'
    | '/departments/$deptId'
    | '/iqac/$tabId'
    | '/nirf/$tabId'
    | '/reports/$id'
    | '/student/dashboard'
    | '/student/login'
    | '/departments/'
    | '/admin/_layout/alumni'
    | '/admin/_layout/announcements'
    | '/admin/_layout/applications'
    | '/admin/_layout/content'
    | '/admin/_layout/courses'
    | '/admin/_layout/dashboard'
    | '/admin/_layout/dynamic-sections'
    | '/admin/_layout/enquiries'
    | '/admin/_layout/events'
    | '/admin/_layout/faculty'
    | '/admin/_layout/feedback'
    | '/admin/_layout/images'
    | '/admin/_layout/news'
    | '/admin/_layout/principal'
    | '/admin/_layout/students'
    | '/admin/_layout/testimonials'
    | '/admin/_layout/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdmissionRoute: typeof AdmissionRoute
  AlumniRoute: typeof AlumniRoute
  ApplyRoute: typeof ApplyRoute
  CalenderRoute: typeof CalenderRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  FacultyRoute: typeof FacultyRoute
  FeedbackRoute: typeof FeedbackRoute
  GalleryRoute: typeof GalleryRoute
  GoverningCouncilRoute: typeof GoverningCouncilRoute
  HodRoute: typeof HodRoute
  HostelRoute: typeof HostelRoute
  InfrastructureRoute: typeof InfrastructureRoute
  LibraryRoute: typeof LibraryRoute
  NewsRoute: typeof NewsRoute
  OfficeRoute: typeof OfficeRoute
  PlacementRoute: typeof PlacementRoute
  PrincipalMessageRoute: typeof PrincipalMessageRoute
  RulesRoute: typeof RulesRoute
  ScholarshipsRoute: typeof ScholarshipsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TimelineRoute: typeof TimelineRoute
  TransportRoute: typeof TransportRoute
  VisionMissionRoute: typeof VisionMissionRoute
  ActivitiesTabIdRoute: typeof ActivitiesTabIdRoute
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AqarTabIdRoute: typeof AqarTabIdRoute
  ComplianceIdRoute: typeof ComplianceIdRoute
  CoursesEMaterialsRoute: typeof CoursesEMaterialsRoute
  CoursesPgRoute: typeof CoursesPgRoute
  CoursesResearchRoute: typeof CoursesResearchRoute
  CoursesUgRoute: typeof CoursesUgRoute
  DepartmentsDeptIdRoute: typeof DepartmentsDeptIdRoute
  IqacTabIdRoute: typeof IqacTabIdRoute
  NirfTabIdRoute: typeof NirfTabIdRoute
  ReportsIdRoute: typeof ReportsIdRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentLoginRoute: typeof StudentLoginRoute
  DepartmentsIndexRoute: typeof DepartmentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vision-mission': {
      id: '/vision-mission'
      path: '/vision-mission'
      fullPath: '/vision-mission'
      preLoaderRoute: typeof VisionMissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport': {
      id: '/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof TransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarships': {
      id: '/scholarships'
      path: '/scholarships'
      fullPath: '/scholarships'
      preLoaderRoute: typeof ScholarshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/principal-message': {
      id: '/principal-message'
      path: '/principal-message'
      fullPath: '/principal-message'
      preLoaderRoute: typeof PrincipalMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placement': {
      id: '/placement'
      path: '/placement'
      fullPath: '/placement'
      preLoaderRoute: typeof PlacementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office': {
      id: '/office'
      path: '/office'
      fullPath: '/office'
      preLoaderRoute: typeof OfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure': {
      id: '/infrastructure'
      path: '/infrastructure'
      fullPath: '/infrastructure'
      preLoaderRoute: typeof InfrastructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hostel': {
      id: '/hostel'
      path: '/hostel'
      fullPath: '/hostel'
      preLoaderRoute: typeof HostelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hod': {
      id: '/hod'
      path: '/hod'
      fullPath: '/hod'
      preLoaderRoute: typeof HodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governing-council': {
      id: '/governing-council'
      path: '/governing-council'
      fullPath: '/governing-council'
      preLoaderRoute: typeof GoverningCouncilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty': {
      id: '/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof FacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calender': {
      id: '/calender'
      path: '/calender'
      fullPath: '/calender'
      preLoaderRoute: typeof CalenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumni': {
      id: '/alumni'
      path: '/alumni'
      fullPath: '/alumni'
      preLoaderRoute: typeof AlumniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admission': {
      id: '/admission'
      path: '/admission'
      fullPath: '/admission'
      preLoaderRoute: typeof AdmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/': {
      id: '/departments/'
      path: '/departments'
      fullPath: '/departments/'
      preLoaderRoute: typeof DepartmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/login': {
      id: '/student/login'
      path: '/student/login'
      fullPath: '/student/login'
      preLoaderRoute: typeof StudentLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$id': {
      id: '/reports/$id'
      path: '/reports/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof ReportsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nirf/$tabId': {
      id: '/nirf/$tabId'
      path: '/nirf/$tabId'
      fullPath: '/nirf/$tabId'
      preLoaderRoute: typeof NirfTabIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iqac/$tabId': {
      id: '/iqac/$tabId'
      path: '/iqac/$tabId'
      fullPath: '/iqac/$tabId'
      preLoaderRoute: typeof IqacTabIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/$deptId': {
      id: '/departments/$deptId'
      path: '/departments/$deptId'
      fullPath: '/departments/$deptId'
      preLoaderRoute: typeof DepartmentsDeptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/ug': {
      id: '/courses/ug'
      path: '/courses/ug'
      fullPath: '/courses/ug'
      preLoaderRoute: typeof CoursesUgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/research': {
      id: '/courses/research'
      path: '/courses/research'
      fullPath: '/courses/research'
      preLoaderRoute: typeof CoursesResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/pg': {
      id: '/courses/pg'
      path: '/courses/pg'
      fullPath: '/courses/pg'
      preLoaderRoute: typeof CoursesPgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/e-materials': {
      id: '/courses/e-materials'
      path: '/courses/e-materials'
      fullPath: '/courses/e-materials'
      preLoaderRoute: typeof CoursesEMaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance/$id': {
      id: '/compliance/$id'
      path: '/compliance/$id'
      fullPath: '/compliance/$id'
      preLoaderRoute: typeof ComplianceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aqar/$tabId': {
      id: '/aqar/$tabId'
      path: '/aqar/$tabId'
      fullPath: '/aqar/$tabId'
      preLoaderRoute: typeof AqarTabIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities/$tabId': {
      id: '/activities/$tabId'
      path: '/activities/$tabId'
      fullPath: '/activities/$tabId'
      preLoaderRoute: typeof ActivitiesTabIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout/users': {
      id: '/admin/_layout/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminLayoutUsersRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/testimonials': {
      id: '/admin/_layout/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminLayoutTestimonialsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/students': {
      id: '/admin/_layout/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminLayoutStudentsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/principal': {
      id: '/admin/_layout/principal'
      path: '/principal'
      fullPath: '/admin/principal'
      preLoaderRoute: typeof AdminLayoutPrincipalRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/news': {
      id: '/admin/_layout/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminLayoutNewsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/images': {
      id: '/admin/_layout/images'
      path: '/images'
      fullPath: '/admin/images'
      preLoaderRoute: typeof AdminLayoutImagesRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/feedback': {
      id: '/admin/_layout/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminLayoutFeedbackRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/faculty': {
      id: '/admin/_layout/faculty'
      path: '/faculty'
      fullPath: '/admin/faculty'
      preLoaderRoute: typeof AdminLayoutFacultyRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/events': {
      id: '/admin/_layout/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminLayoutEventsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/enquiries': {
      id: '/admin/_layout/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminLayoutEnquiriesRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/dynamic-sections': {
      id: '/admin/_layout/dynamic-sections'
      path: '/dynamic-sections'
      fullPath: '/admin/dynamic-sections'
      preLoaderRoute: typeof AdminLayoutDynamicSectionsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/dashboard': {
      id: '/admin/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminLayoutDashboardRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/courses': {
      id: '/admin/_layout/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminLayoutCoursesRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/content': {
      id: '/admin/_layout/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminLayoutContentRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/applications': {
      id: '/admin/_layout/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminLayoutApplicationsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/announcements': {
      id: '/admin/_layout/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminLayoutAnnouncementsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/alumni': {
      id: '/admin/_layout/alumni'
      path: '/alumni'
      fullPath: '/admin/alumni'
      preLoaderRoute: typeof AdminLayoutAlumniRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
  }
}

interface AdminLayoutRouteChildren {
  AdminLayoutAlumniRoute: typeof AdminLayoutAlumniRoute
  AdminLayoutAnnouncementsRoute: typeof AdminLayoutAnnouncementsRoute
  AdminLayoutApplicationsRoute: typeof AdminLayoutApplicationsRoute
  AdminLayoutContentRoute: typeof AdminLayoutContentRoute
  AdminLayoutCoursesRoute: typeof AdminLayoutCoursesRoute
  AdminLayoutDashboardRoute: typeof AdminLayoutDashboardRoute
  AdminLayoutDynamicSectionsRoute: typeof AdminLayoutDynamicSectionsRoute
  AdminLayoutEnquiriesRoute: typeof AdminLayoutEnquiriesRoute
  AdminLayoutEventsRoute: typeof AdminLayoutEventsRoute
  AdminLayoutFacultyRoute: typeof AdminLayoutFacultyRoute
  AdminLayoutFeedbackRoute: typeof AdminLayoutFeedbackRoute
  AdminLayoutImagesRoute: typeof AdminLayoutImagesRoute
  AdminLayoutNewsRoute: typeof AdminLayoutNewsRoute
  AdminLayoutPrincipalRoute: typeof AdminLayoutPrincipalRoute
  AdminLayoutStudentsRoute: typeof AdminLayoutStudentsRoute
  AdminLayoutTestimonialsRoute: typeof AdminLayoutTestimonialsRoute
  AdminLayoutUsersRoute: typeof AdminLayoutUsersRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutAlumniRoute: AdminLayoutAlumniRoute,
  AdminLayoutAnnouncementsRoute: AdminLayoutAnnouncementsRoute,
  AdminLayoutApplicationsRoute: AdminLayoutApplicationsRoute,
  AdminLayoutContentRoute: AdminLayoutContentRoute,
  AdminLayoutCoursesRoute: AdminLayoutCoursesRoute,
  AdminLayoutDashboardRoute: AdminLayoutDashboardRoute,
  AdminLayoutDynamicSectionsRoute: AdminLayoutDynamicSectionsRoute,
  AdminLayoutEnquiriesRoute: AdminLayoutEnquiriesRoute,
  AdminLayoutEventsRoute: AdminLayoutEventsRoute,
  AdminLayoutFacultyRoute: AdminLayoutFacultyRoute,
  AdminLayoutFeedbackRoute: AdminLayoutFeedbackRoute,
  AdminLayoutImagesRoute: AdminLayoutImagesRoute,
  AdminLayoutNewsRoute: AdminLayoutNewsRoute,
  AdminLayoutPrincipalRoute: AdminLayoutPrincipalRoute,
  AdminLayoutStudentsRoute: AdminLayoutStudentsRoute,
  AdminLayoutTestimonialsRoute: AdminLayoutTestimonialsRoute,
  AdminLayoutUsersRoute: AdminLayoutUsersRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdmissionRoute: AdmissionRoute,
  AlumniRoute: AlumniRoute,
  ApplyRoute: ApplyRoute,
  CalenderRoute: CalenderRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  FacultyRoute: FacultyRoute,
  FeedbackRoute: FeedbackRoute,
  GalleryRoute: GalleryRoute,
  GoverningCouncilRoute: GoverningCouncilRoute,
  HodRoute: HodRoute,
  HostelRoute: HostelRoute,
  InfrastructureRoute: InfrastructureRoute,
  LibraryRoute: LibraryRoute,
  NewsRoute: NewsRoute,
  OfficeRoute: OfficeRoute,
  PlacementRoute: PlacementRoute,
  PrincipalMessageRoute: PrincipalMessageRoute,
  RulesRoute: RulesRoute,
  ScholarshipsRoute: ScholarshipsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TimelineRoute: TimelineRoute,
  TransportRoute: TransportRoute,
  VisionMissionRoute: VisionMissionRoute,
  ActivitiesTabIdRoute: ActivitiesTabIdRoute,
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AqarTabIdRoute: AqarTabIdRoute,
  ComplianceIdRoute: ComplianceIdRoute,
  CoursesEMaterialsRoute: CoursesEMaterialsRoute,
  CoursesPgRoute: CoursesPgRoute,
  CoursesResearchRoute: CoursesResearchRoute,
  CoursesUgRoute: CoursesUgRoute,
  DepartmentsDeptIdRoute: DepartmentsDeptIdRoute,
  IqacTabIdRoute: IqacTabIdRoute,
  NirfTabIdRoute: NirfTabIdRoute,
  ReportsIdRoute: ReportsIdRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentLoginRoute: StudentLoginRoute,
  DepartmentsIndexRoute: DepartmentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
