/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisionMissionRouteImport } from './routes/vision-mission'
import { Route as TransportRouteImport } from './routes/transport'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrincipalMessageRouteImport } from './routes/principal-message'
import { Route as PlacementRouteImport } from './routes/placement'
import { Route as NewsRouteImport } from './routes/news'
import { Route as LibrarysRouteImport } from './routes/library'
import { Route as InfrastructureRouteImport } from './routes/infrastructure'
import { Route as HostelRouteImport } from './routes/hostel'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FacultyRouteImport } from './routes/faculty'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DepartmentsRouteImport } from './routes/departments.index'
import { Route as CoursesRouteImport } from './routes/courses.ug'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AdmissionRouteImport } from './routes/admission'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentLoginRouteImport } from './routes/student/login'
import { Route as StudentDashboardRouteImport } from './routes/student/dashboard'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as AdminLayoutUsersRouteImport } from './routes/admin/_layout.users'
import { Route as AdminLayoutStudentsRouteImport } from './routes/admin/_layout.students'
import { Route as AdminLayoutNewsRouteImport } from './routes/admin/_layout.news'
import { Route as AdminLayoutEventsRouteImport } from './routes/admin/_layout.events'
import { Route as AdminLayoutDashboardRouteImport } from './routes/admin/_layout.dashboard'
import { Route as AdminLayoutContentRouteImport } from './routes/admin/_layout.content'
import { Route as AdminLayoutApplicationsRouteImport } from './routes/admin/_layout.applications'
import { Route as AdminLayoutAnnouncementsRouteImport } from './routes/admin/_layout.announcements'

const VisionMissionRoute = VisionMissionRouteImport.update({
  id: '/vision-mission',
  path: '/vision-mission',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportRoute = TransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrincipalMessageRoute = PrincipalMessageRouteImport.update({
  id: '/principal-message',
  path: '/principal-message',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacementRoute = PlacementRouteImport.update({
  id: '/placement',
  path: '/placement',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrarysRoute = LibrarysRouteImport.update({
  id: '/librarys',
  path: '/librarys',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructureRoute = InfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => rootRouteImport,
} as any)
const HostelRoute = HostelRouteImport.update({
  id: '/hostel',
  path: '/hostel',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRoute = FacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionRoute = AdmissionRouteImport.update({
  id: '/admission',
  path: '/admission',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLoginRoute = StudentLoginRouteImport.update({
  id: '/student/login',
  path: '/student/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutUsersRoute = AdminLayoutUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutStudentsRoute = AdminLayoutStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutNewsRoute = AdminLayoutNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutEventsRoute = AdminLayoutEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutDashboardRoute = AdminLayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutContentRoute = AdminLayoutContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutApplicationsRoute = AdminLayoutApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutAnnouncementsRoute =
  AdminLayoutAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admission': typeof AdmissionRoute
  '/apply': typeof ApplyRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/departments': typeof DepartmentsRoute
  '/events': typeof EventsRoute
  '/faculty': typeof FacultyRoute
  '/gallery': typeof GalleryRoute
  '/hostel': typeof HostelRoute
  '/infrastructure': typeof InfrastructureRoute
  '/librarys': typeof LibrarysRoute
  '/news': typeof NewsRoute
  '/placement': typeof PlacementRoute
  '/principal-message': typeof PrincipalMessageRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/timeline': typeof TimelineRoute
  '/transport': typeof TransportRoute
  '/vision-mission': typeof VisionMissionRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/login': typeof StudentLoginRoute
  '/admin/announcements': typeof AdminLayoutAnnouncementsRoute
  '/admin/applications': typeof AdminLayoutApplicationsRoute
  '/admin/content': typeof AdminLayoutContentRoute
  '/admin/dashboard': typeof AdminLayoutDashboardRoute
  '/admin/events': typeof AdminLayoutEventsRoute
  '/admin/news': typeof AdminLayoutNewsRoute
  '/admin/students': typeof AdminLayoutStudentsRoute
  '/admin/users': typeof AdminLayoutUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admission': typeof AdmissionRoute
  '/apply': typeof ApplyRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/departments': typeof DepartmentsRoute
  '/events': typeof EventsRoute
  '/faculty': typeof FacultyRoute
  '/gallery': typeof GalleryRoute
  '/hostel': typeof HostelRoute
  '/infrastructure': typeof InfrastructureRoute
  '/librarys': typeof LibrarysRoute
  '/news': typeof NewsRoute
  '/placement': typeof PlacementRoute
  '/principal-message': typeof PrincipalMessageRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/timeline': typeof TimelineRoute
  '/transport': typeof TransportRoute
  '/vision-mission': typeof VisionMissionRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/login': typeof StudentLoginRoute
  '/admin/announcements': typeof AdminLayoutAnnouncementsRoute
  '/admin/applications': typeof AdminLayoutApplicationsRoute
  '/admin/content': typeof AdminLayoutContentRoute
  '/admin/dashboard': typeof AdminLayoutDashboardRoute
  '/admin/events': typeof AdminLayoutEventsRoute
  '/admin/news': typeof AdminLayoutNewsRoute
  '/admin/students': typeof AdminLayoutStudentsRoute
  '/admin/users': typeof AdminLayoutUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admission': typeof AdmissionRoute
  '/apply': typeof ApplyRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/departments': typeof DepartmentsRoute
  '/events': typeof EventsRoute
  '/faculty': typeof FacultyRoute
  '/gallery': typeof GalleryRoute
  '/hostel': typeof HostelRoute
  '/infrastructure': typeof InfrastructureRoute
  '/librarys': typeof LibrarysRoute
  '/news': typeof NewsRoute
  '/placement': typeof PlacementRoute
  '/principal-message': typeof PrincipalMessageRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/timeline': typeof TimelineRoute
  '/transport': typeof TransportRoute
  '/vision-mission': typeof VisionMissionRoute
  '/admin/_layout': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/login': typeof StudentLoginRoute
  '/admin/_layout/announcements': typeof AdminLayoutAnnouncementsRoute
  '/admin/_layout/applications': typeof AdminLayoutApplicationsRoute
  '/admin/_layout/content': typeof AdminLayoutContentRoute
  '/admin/_layout/dashboard': typeof AdminLayoutDashboardRoute
  '/admin/_layout/events': typeof AdminLayoutEventsRoute
  '/admin/_layout/news': typeof AdminLayoutNewsRoute
  '/admin/_layout/students': typeof AdminLayoutStudentsRoute
  '/admin/_layout/users': typeof AdminLayoutUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admission'
    | '/apply'
    | '/contact'
    | '/courses'
    | '/departments'
    | '/events'
    | '/faculty'
    | '/gallery'
    | '/hostel'
    | '/infrastructure'
    | '/librarys'
    | '/news'
    | '/placement'
    | '/principal-message'
    | '/sitemap.xml'
    | '/timeline'
    | '/transport'
    | '/vision-mission'
    | '/admin'
    | '/admin/login'
    | '/student/dashboard'
    | '/student/login'
    | '/admin/announcements'
    | '/admin/applications'
    | '/admin/content'
    | '/admin/dashboard'
    | '/admin/events'
    | '/admin/news'
    | '/admin/students'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admission'
    | '/apply'
    | '/contact'
    | '/courses'
    | '/departments'
    | '/events'
    | '/faculty'
    | '/gallery'
    | '/hostel'
    | '/infrastructure'
    | '/librarys'
    | '/news'
    | '/placement'
    | '/principal-message'
    | '/sitemap.xml'
    | '/timeline'
    | '/transport'
    | '/vision-mission'
    | '/admin'
    | '/admin/login'
    | '/student/dashboard'
    | '/student/login'
    | '/admin/announcements'
    | '/admin/applications'
    | '/admin/content'
    | '/admin/dashboard'
    | '/admin/events'
    | '/admin/news'
    | '/admin/students'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admission'
    | '/apply'
    | '/contact'
    | '/courses'
    | '/departments'
    | '/events'
    | '/faculty'
    | '/gallery'
    | '/hostel'
    | '/infrastructure'
    | '/librarys'
    | '/news'
    | '/placement'
    | '/principal-message'
    | '/sitemap.xml'
    | '/timeline'
    | '/transport'
    | '/vision-mission'
    | '/admin/_layout'
    | '/admin/login'
    | '/student/dashboard'
    | '/student/login'
    | '/admin/_layout/announcements'
    | '/admin/_layout/applications'
    | '/admin/_layout/content'
    | '/admin/_layout/dashboard'
    | '/admin/_layout/events'
    | '/admin/_layout/news'
    | '/admin/_layout/students'
    | '/admin/_layout/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdmissionRoute: typeof AdmissionRoute
  ApplyRoute: typeof ApplyRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRoute
  DepartmentsRoute: typeof DepartmentsRoute
  EventsRoute: typeof EventsRoute
  FacultyRoute: typeof FacultyRoute
  GalleryRoute: typeof GalleryRoute
  HostelRoute: typeof HostelRoute
  InfrastructureRoute: typeof InfrastructureRoute
  LibrarysRoute: typeof LibrarysRoute
  NewsRoute: typeof NewsRoute
  PlacementRoute: typeof PlacementRoute
  PrincipalMessageRoute: typeof PrincipalMessageRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TimelineRoute: typeof TimelineRoute
  TransportRoute: typeof TransportRoute
  VisionMissionRoute: typeof VisionMissionRoute
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentLoginRoute: typeof StudentLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vision-mission': {
      id: '/vision-mission'
      path: '/vision-mission'
      fullPath: '/vision-mission'
      preLoaderRoute: typeof VisionMissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport': {
      id: '/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof TransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/principal-message': {
      id: '/principal-message'
      path: '/principal-message'
      fullPath: '/principal-message'
      preLoaderRoute: typeof PrincipalMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placement': {
      id: '/placement'
      path: '/placement'
      fullPath: '/placement'
      preLoaderRoute: typeof PlacementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/librarys': {
      id: '/librarys'
      path: '/librarys'
      fullPath: '/librarys'
      preLoaderRoute: typeof LibrarysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure': {
      id: '/infrastructure'
      path: '/infrastructure'
      fullPath: '/infrastructure'
      preLoaderRoute: typeof InfrastructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hostel': {
      id: '/hostel'
      path: '/hostel'
      fullPath: '/hostel'
      preLoaderRoute: typeof HostelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty': {
      id: '/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof FacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admission': {
      id: '/admission'
      path: '/admission'
      fullPath: '/admission'
      preLoaderRoute: typeof AdmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/login': {
      id: '/student/login'
      path: '/student/login'
      fullPath: '/student/login'
      preLoaderRoute: typeof StudentLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout/users': {
      id: '/admin/_layout/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminLayoutUsersRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/students': {
      id: '/admin/_layout/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminLayoutStudentsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/news': {
      id: '/admin/_layout/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminLayoutNewsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/events': {
      id: '/admin/_layout/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminLayoutEventsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/dashboard': {
      id: '/admin/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminLayoutDashboardRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/content': {
      id: '/admin/_layout/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminLayoutContentRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/applications': {
      id: '/admin/_layout/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminLayoutApplicationsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/announcements': {
      id: '/admin/_layout/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminLayoutAnnouncementsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
  }
}

interface AdminLayoutRouteChildren {
  AdminLayoutAnnouncementsRoute: typeof AdminLayoutAnnouncementsRoute
  AdminLayoutApplicationsRoute: typeof AdminLayoutApplicationsRoute
  AdminLayoutContentRoute: typeof AdminLayoutContentRoute
  AdminLayoutDashboardRoute: typeof AdminLayoutDashboardRoute
  AdminLayoutEventsRoute: typeof AdminLayoutEventsRoute
  AdminLayoutNewsRoute: typeof AdminLayoutNewsRoute
  AdminLayoutStudentsRoute: typeof AdminLayoutStudentsRoute
  AdminLayoutUsersRoute: typeof AdminLayoutUsersRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutAnnouncementsRoute: AdminLayoutAnnouncementsRoute,
  AdminLayoutApplicationsRoute: AdminLayoutApplicationsRoute,
  AdminLayoutContentRoute: AdminLayoutContentRoute,
  AdminLayoutDashboardRoute: AdminLayoutDashboardRoute,
  AdminLayoutEventsRoute: AdminLayoutEventsRoute,
  AdminLayoutNewsRoute: AdminLayoutNewsRoute,
  AdminLayoutStudentsRoute: AdminLayoutStudentsRoute,
  AdminLayoutUsersRoute: AdminLayoutUsersRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdmissionRoute: AdmissionRoute,
  ApplyRoute: ApplyRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRoute,
  DepartmentsRoute: DepartmentsRoute,
  EventsRoute: EventsRoute,
  FacultyRoute: FacultyRoute,
  GalleryRoute: GalleryRoute,
  HostelRoute: HostelRoute,
  InfrastructureRoute: InfrastructureRoute,
  LibrarysRoute: LibrarysRoute,
  NewsRoute: NewsRoute,
  PlacementRoute: PlacementRoute,
  PrincipalMessageRoute: PrincipalMessageRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TimelineRoute: TimelineRoute,
  TransportRoute: TransportRoute,
  VisionMissionRoute: VisionMissionRoute,
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentLoginRoute: StudentLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
